### ISSUE TITLE
Production app broken after the latest deploy

### ISSUE THREAD

**Issue by arunsathiya** [youknowriad/asblocks#14]
asblocks.com does not load after the latest deploy: https://github.com/youknowriad/asblocks/pull/6

It was working fine before that merge. 

I see this on console: 

```
ReferenceError: $RefreshSig$ is not definedmain.js:356:299501
    <anonymous> https://asblocks.com/main.js:356
    n https://asblocks.com/main.js:1
    <anonymous> https://asblocks.com/main.js:1
    <anonymous> https://asblocks.com/main.js:1
```

Tested on Brave Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit) and Firefox.

**Comment by arunsathiya** [comment]
Building the app locally works. And, I do not see a similar error on the local build.

**Comment by epiqueras** [comment]
The development build was being deployed. It's fixed now.

Thanks for reporting so quickly 😄
