### ISSUE TITLE
Initial share does not save content to cloud

### ISSUE THREAD

**Issue by arunsathiya** [youknowriad/asblocks#17]
- Visit asblocks.com
- Enter a title and some content
- Click `Share`
- Copy the write/read link and share with the recipient

Upon loading that link, file content is expected to be visible. But there isn't any, because initial share **does not** trigger an auto-save to cloud. 

Only upon closing share modals' popup, we see a `Save` button. Clicking on it would save the content for the first time ever.

**Comment by youknowriad** [comment]
> Upon loading that link, file content is expected to be visible. But there isn't any, because initial share does not trigger an auto-save to cloud.

That's because the "init" action from the socket didn't arrive yet, we should probably keep the loading screen until it arrives in that case.
