### ISSUE TITLE
SentryError: Invalid Dsn

### ISSUE THREAD

**Issue by ItsJonQ** [youknowriad/asblocks#34]
👋 Haiii! I'm interesting in contributing to this project 😊 .
I tried firing it up locally, but I'm seeing this error:

<img width="1053" alt="Screen Shot 2020-06-23 at 12 51 18 PM" src="https://user-images.githubusercontent.com/2322354/85432036-5bc6fc80-b550-11ea-839f-ce5baa400bb7.png">

I followed the instructions in the README.

Not sure if I have to do something.

Thank you!

**Comment by epiqueras** [comment]
Don't have a `sentry` entry in your `config/index.js`.

**Comment by ItsJonQ** [comment]
@epiqueras Oh! Hmm. How do I get one of those. Do I need to sign up for a Sentry account?

**Comment by epiqueras** [comment]
No, I meant you shouldn't have an entry at all.

https://github.com/youknowriad/asblocks/blob/4f88963f9b99ff3f37c8c0b3dea1c7b01a3dc9b8/src/index.js#L10-L12

So that doesn't run.

**Comment by ItsJonQ** [comment]
I followed the instructions to copy the `index.sample.js` to `index.js`.

```
export const config = {
	collabServer: '${{ secrets.COLLAB_SERVER }}',
	sentry: '${{ secrets.SENTRY_DSN }}',
};
```

That's what it has in the `config.sentry`

That's all I know 😊
