### ISSUE TITLE
body background color not set by default

### ISSUE THREAD

**Issue by joyously** [youknowriad/asblocks#40]
I have my browser default color set to yellow, as you can see.
I had to highlight the Share button in order to read it, trying to figure out what this page does.
![AsBlocks-31](https://user-images.githubusercontent.com/7957680/87606412-88d67d00-c6c0-11ea-89e2-c95ea96ff659.jpg)

**Comment by youknowriad** [comment]
Thanks for the issue @joyously I think the button is disabled still until you enter content.

**Comment by joyously** [comment]
Yes, I realize it was disabled. I was just saying what my experience was. I couldn't tell what the page was about and I couldn't read the one thing that sort of looked like a button.

**Comment by youknowriad** [comment]
The disabled button comes from `@wordpress/components` so likely a Gutenberg issue. That said, I think after a minute of typing around, I feel and after clicking "share" for the first time, you might start to understand the tool. 

Thanks for the insights, I'll keep those in mind when If I ever try to improve the NUX experience.
