### ISSUE TITLE
Clicking the quick-inserter (canvas inserter) triggers a JS error and a blank page.

### ISSUE THREAD

**Issue by youknowriad** [youknowriad/asblocks#43]

**Comment by simulieren** [comment]
@youknowriad I had the same problem with my custom editor. 
The fixed this by adding these two arrays to the settings of the `BlockEditorProvider`:

```js
const settings = {
...,
__experimentalBlockPatterns: [],
__experimentalBlockPatternCategories: [],
}
```

**Comment by youknowriad** [comment]
@simulieren Thanks, that's very helpful, I guess ideally we fix that on Gutenberg itself and avoid the need to explicitly set these settings.
