### ISSUE TITLE
Chrome tab is freezing when I try to insert a block.

### ISSUE THREAD

**Issue by KhaldiAmer** [youknowriad/asblocks#47]

**Comment by youknowriad** [comment]
Yes, I noticed that sometimes too, it seems that there's some "infinite loop" between the editor updates and the updates that come from the socket server. Not sure I'd have much time to debug that in the next days.

**Comment by KhaldiAmer** [comment]
I'll try to do that when I have time. Does the Heroku production server run with no problem?

**Comment by youknowriad** [comment]
yes, I think so you

**Comment by youknowriad** [comment]
This is fixed in 3d4ee6d

Let me know if you experience any issues now.
