### ISSUE TITLE
Blank for READ link

### ISSUE THREAD

**Issue by Lewiscowles1986** [youknowriad/asblocks#48]
I Have no idea why but adding a title and nonsense paragraph, I got this when I go to read.

https://asblocks.com/read/9QJDOmdgCejUP3jpTztG#key=V7xxkxYRvYBn16G00qpKmQ

It's just a white screen. 

I do not know if this is documentation need (maybe I'm at fault somehow), or a bug, but it's made me curious

**Comment by Lewiscowles1986** [comment]
Hmm... Leaning towards documentation. I edited and saw a save button appear. Clicking that as original author now means the original link loads.

**Comment by youknowriad** [comment]
Yeah, right now the "read" link only shows the explicitely saved version. We may want to revisit that.

**Comment by Lewiscowles1986** [comment]
I think we're saying the same thing, but just to confirm.

This is not a ticket that auto-save isn't happening.

It's that I made a layout, and upon clicking share, what I'd done at that point was not shared, but rather a blank screen.

After seeing that blank screen I checked the console for errors and network tab for dropped / error HTTP requests. Nothing so I wrote this.

At some point after (likely within minutes) I noticed a save button and decided to make an edit and use that. It worked as expected.

**Comment by youknowriad** [comment]
yes, that's how it works now. When you "share" you get two links: once is the "write"  version where changes are synced across collaborators using the editor instantaneously and the "read" link where only "saved" changes are visible.

I think it's confusing and I'd like to implement autosaving to solve this. There's an issue for that #37
