### ISSUE TITLE
Flashing toolbar when typing.

### ISSUE THREAD

**Issue by KhaldiAmer** [youknowriad/asblocks#58]
I guess it happens when the state updates. Maybe we can debounce the state updates?

**Comment by youknowriad** [comment]
If I'm not wrong, the toolbar is supposed to disappear when typing and only appear back when you move the mouse.

**Comment by KhaldiAmer** [comment]
I want to give this a try, any hints would be helpful!

**Comment by KhaldiAmer** [comment]
Didn't notice my mouse was moving while I was typing. That was the issue.
